title: 
 <p align="center">
   Turner Luke
 </p>
 
logo: "/images/myFaceCirc.png?raw=true"  # Bio image

description: > # Bio text (Left side)
  
  <p align="center">
    <a href="https://www.linkedin.com/in/turnermluke/">
       <img src=https://img.shields.io/badge/LinkedIn-0077B5?style=for-the-badge&logo=linkedin&logoColor=white
       height=35>
    </a>
    <a href=https://github.com/turnerluke/turnerluke/blob/main/Turner%20Luke%20Resume.pdf>
       <img src=https://img.shields.io/static/v1?label=&message=Resume&color=red&style=for-the-badge
       height=35>
    </a>
    <a href=https://medium.com/@turnermluke>
       <img src=https://img.shields.io/badge/Medium-12100E?style=for-the-badge&logo=medium&logoColor=white 
       height=35>
    </a>
    <a href=https://github.com/turnerluke>
       <img src=https://img.shields.io/badge/GitHub-100000?style=for-the-badge&logo=github&logoColor=white
       height=35>
    </a>

    
  </p>
  
  <img src= /images/map_pin.png height=24>   Austin, Texas
  
  
  <br>
  
  <img src= /images/map_pin.png height=24>
  <style>
.intro {
  width: 200px;
;
}
</style>

<body>

<div class="intro">
Austin, Texas
</div>

</body>
  
  <br>
  <br>
  
  Medical device engineer seeking to translate passion for quantitative analysis into a data science career.
  
  <br>
  <br>
  
  Graduated from The University of Wisconsin - Madison with B.S. Chemical Engineering, Chemistry double major.
  
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
